#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace uds.CRM.Model
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class UdsContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public UdsContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="uds.CRM.Model.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<uds.CRM.Model.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<uds.CRM.Model.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="uds.CRM.Model.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<uds.CRM.Model.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<uds.CRM.Model.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="uds.CRM.Model.Task"/> entities.
		/// </summary>
		public System.Linq.IQueryable<uds.CRM.Model.Task> TaskSet
		{
			get
			{
				return this.CreateQuery<uds.CRM.Model.Task>();
			}
		}
	}
}
#pragma warning restore CS1591
